name: postify
description: Election and Festival Banner/Poster Maker
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  
  # UI & Navigation
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  
  # Image Processing
  image_picker: ^1.0.4
  image: ^4.1.3
  flutter_colorpicker: ^1.0.3
  
  # Canvas & Drawing
  flutter_signature_pad: ^3.0.1
  
  # File & Storage
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  
  # Sharing & Export
  share_plus: ^7.2.1
  permission_handler: ^11.0.1
  
  # Monetization
  google_mobile_ads: ^4.0.0
  razorpay_flutter: ^1.3.6
  
  # Utilities
  uuid: ^4.2.1
  intl: ^0.18.1
  connectivity_plus: ^5.0.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/templates/
    - assets/icons/
